### PR TITLE
Add int and odo and autotime where necessary

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by koverholt** [comment]
Thanks! The autotime extension adds a lot of extra text to an already-long blog post, so I don't think I will use it here. I will definitely use the cleaner %time syntax.

**Comment by cpcloud** [comment]
Ok i'll remove the autotime stuff

**Comment by koverholt** [comment]
No worries, I'll add the better %time syntax my existing PR, I'm working in the notebook already. Unless you want to make any other changes?

**Comment by cpcloud** [comment]
nope that's it

**Comment by koverholt** [comment]
Fixed %time syntax in commit 60c71f5. Thanks for the tip!

**Pull request closed without merging**
